### ISSUE TITLE
When using pastrecords, the donation date becomes the creation date

### ISSUE THREAD

**Issue by windchime-yk** [azu/philan.net#45]
過去の記録から新しい寄付を記録する際に、寄付した日付を変更しても作成日で記録されてしまいます。

## 再現手順
1. 新しい寄付の記録ページを開く
2. 『過去の記録から入力する』から過去の記録を選択
3. 日付を変更
4. Submitを押下

**Comment by azu** [comment]
ご報告ありがとうございます！
#46 で修正してみました。
