### ISSUE TITLE
Feature: Make it possible to use `<MenuItem>` like `<a>` tags

### ISSUE THREAD

**Issue by yamanoku** [azu/philan.net#57]
philan.net 使わせてもらっている者です。
いつどのような寄付ができたかが確認できて便利に使うことができてありがたいです。

要望なのですが、ユーザーアイコンをクリックしたときに表示されるメニュー項目をリンクタグのように扱ってほしいです。

<img width="285" alt="自分のアイコンを押下したのち、メニューが開かれて「Open My Page」「Open SpreadSheet」「Edit Profile」のリストが表示されている" src="https://user-images.githubusercontent.com/1996642/136689297-adca4377-52ba-43f1-910f-c13339162960.png">

理由としてはマイページを別タブで開けるようにして、入力するときに過去 Submit したものはないかタブごとで確認できるようにしたいと思っているからです。
現状これができないため、ブラウザの前に戻るから別タブで開くようにして見ています。

ソースを確認したところ [chakra-ui の Menu コンポーネント](https://chakra-ui.com/docs/overlay/menu#customizing-the-button)から `<MenuItem>` を使用しているようですが、この内部は `<button>` として使用されており、`<a>` タグでのリンクのように右クリックでメニューを表示させたり、`command` ボタンと同時にクリックするなどして別タブで開くなどが現状できません。

これがないと非常に困るということではなく、あると便利だなと思っている程度なので、そういった温度感で見てもらえるとありがたいです。

**Comment by azu** [comment]
MenuItem > Linkとするか
`<MenuItem as="a">` のようにリンクすることで解決できそうな気がしますね。
(ChakraUI的な正しい解決方法がまだ良くわかってないですが)
