### ISSUE TITLE
Display 400 when access user own page

### ISSUE THREAD

**Issue by kyoncy** [azu/philan.net#58]
寄付に関しての関心が高まったこともあり philan.net を使わせてもらっています。
簡単に管理できるので使い続けようと思っています。

私自身のユーザーページにアクセスすると400が表示されてしまうため報告させていただきました。
https://philan.net/user/kyoncy

json, feed に関しては取得可能です。
- https://philan.net/user/kyoncy/json
- https://philan.net/user/kyoncy/feed

**Comment by azu** [comment]
ちょっとユーザ一覧に使ってるKVSのデータがおかしくなってる気がしますね。
調べてみます。

**Comment by kyoncy** [comment]
対応してくださりありがとうございます。
今確認したところ、ユーザーページが問題なく表示されました。
